[package]
name = "tauri-plugin-mobile"
version.workspace = true
edition = "2021"
links = "tauri-plugin-mobile"
license = "GPL-3.0"

[dependencies]
tauri.workspace = true
serde.workspace = true
serde_json.workspace = true

[build-dependencies]
tauri-plugin = { version = "=2.5.3", features = ["build"] }
